### ISSUE TITLE
Check.Seq.forall

### ISSUE THREAD

**Issue by sheridanchris** [pimbrouwers/Validus#34]
Tests if all elements of the sequence satisfy the given predicate.
```fsharp
Check.Seq.equalsLen 6 <+> Check.Seq.forall Char.IsNumber
```

**Comment by iskandersierra** [comment]
Just now I created this function `arrayOf`. It left me wondering whether a similar built-in validator already existed for `Check.Seq` or `Check.Array`.

```fsharp
let arrayOf (validator: Validator<'a, 'a>) : Validator<'a [], 'a []> =
    fun field input ->
        let results = Array.zeroCreate input.Length
        let mutable errors = ValidationErrors.create field []

        for i = 0 to input.Length - 1 do
            match validator (subIndexFor field i) input.[i] with
            | Ok result ->
                results.[i] <- result
            | Error error ->
                errors <- ValidationErrors.merge errors error

        if ValidationErrors.toMap errors |> Map.isEmpty then
            Ok results
        else
            Error errors
```

Also, I couldn't find any `ValidationErrors.hasErrors` or `ValidationErrors.isEmpty` equivalent. I used here `ValidationErrors.toMap errors |> Map.isEmpty` only because I looked into the source code to ensure I wasn't incurring into any costly operations.

> NOTE: `let subIndexFor = sprintf "%s[%i]"`
